# Generated by Django 3.0.5 on 2020-04-21 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200413_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Company Name', max_length=200)),
                ('customer_content', models.TextField(blank=True, null=True)),
                ('customer_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('customer_imageurl', models.CharField(default='static/main/images/no-image.jpg', max_length=200)),
                ('customer_link', models.CharField(blank=True, default='https://en.wikipedia.org/wiki/ConocoPhillips', max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
