# Generated by Django 3.0.5 on 2020-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200421_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
